---

AWSTemplateFormatVersion: "2010-09-09"

Parameters:
  TopicName:
    Type: String
    Description: Name of the sns topic
    Default: ashtest-01

Resources:
  MyTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: !Ref TopicName

Outputs:
  SNSTopicARN:
    Description: ARN of the SNS Topic
    Value: !Ref MyTopic
