# CloudFormation to ADD S3 Bucket
#
# Usage: aws cloudformation create-stack --stack-name david-create-s3 --template-body file://lab2-s3-cf.yaml --capabilities CAPABILITY_NAMED_IAM
#
# Validate: aws cloudformation validate-template --template-body file://lab2-s3-cf.yaml
#
#
Resources:
  davids3bucket:
      Type: 'AWS::S3::Bucket'
      Properties: 
        BucketName: 'david-s3-bucket-cf' 

  sampleBucketPolicy:
      Type: AWS::S3::BucketPolicy
      Properties:
        Bucket: #'david-s3-bucket-cf'
          Ref: "davids3bucket"
        PolicyDocument:
          Statement:
            -
              Action:
                - "s3:GetObject"
              Effect: "Allow"
              Resource:
                  - 'arn:aws:s3:::david-s3-bucket-cf'
              Resource:
                  - 'arn:aws:s3:::david-s3-bucket-cf/*'
              Principal: "*"
  iamuser:
    Type: 'AWS::IAM::User'
    Properties:
      UserName: 'iam-david-s3-user'

  iamgroup:
    Type: 'AWS::IAM::Group'
    Properties:
      GroupName: 'iam-david-s3-group'

  iamassociation:
    Type: 'AWS::IAM::UserToGroupAddition'
    Properties:
      GroupName: 'iam-david-s3-group'
      Users:
      - !Ref iamuser
